---
services:
  busy:
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    secrets:
      - test
    deploy:
      placement:
        constraints:
          - node.labels.busy==ok
      resources:
        limits:
          cpus: "0.8"
        reservations:
          cpus: "0.2"

secrets:
  test:
    name: mariadb
    external: true
