---
name: busystack
services:
  busysvc:
    image: busybox:1.28
    container_name: busy
    hostname: busycnt
    command:
      - sleep
      - "3600"
    environment:
      - STAGE=DOCKER
      - JOURS=5
    ports:
      - 8080:80
    volumes:
      - data:/partage
      - ./data:/data
    networks:
      busynet:
        ipv4_address: 172.20.0.100
    restart: unless-stopped

volumes:
  data:

networks:
  busynet:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.255.254
    driver_opts:
      com.docker.network.bridge.name: busynet0
