---
services:
  who-1:
    image: traefik/whoami
    container_name: who-1
    hostname: who-1
    restart: unless-stopped
    networks:
      - proxynet
      - whonet
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.routers.who1.rule=Host(`who-1.stage.local`)

  who-2:
    image: traefik/whoami
    container_name: who-2
    hostname: who-2
    restart: unless-stopped
    networks:
      - proxynet
      - whonet
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.routers.who2.rule=PathPrefix(`/who-2`)
      - traefik.http.middlewares.who2strip.stripprefix.prefixes=/who-2
      - traefik.http.routers.who2.middlewares=who2strip

  who-3:
    image: traefik/whoami
    container_name: who-3
    hostname: who-3
    restart: unless-stopped
    networks:
      - proxynet
      - whonet
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.routers.who3.rule=(Host(`who-3.stage.local`) && PathPrefix(`/who-3`))
      - traefik.http.middlewares.who3strip.stripprefix.prefixes=/who-3
      - traefik.http.routers.who3.middlewares=who3strip

networks:
  whonet:
  proxynet:
    external: true
