---
name: lemp

services:
  www:
    image: nginx:1.28
    container_name: www
    hostname: www
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      lempnet:
        ipv4_address: 172.40.0.100
    restart: unless-stopped

  php:
    image: php:8.2-fpm
    container_name: php
    hostname: php
    volumes:
      - ./html:/var/www/html
    networks:
      lempnet:
        ipv4_address: 172.40.0.110
    restart: unless-stopped

  db:
    image: mariadb:11.8.2
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=azerty
    volumes:
      - datadb:/var/lib/mysql
    networks:
      lempnet:
        ipv4_address: 172.40.0.120
    restart: unless-stopped

volumes:
  datadb:

networks:
  lempnet:
    ipam:
      config:
        - subnet: 172.40.0.0/16
          gateway: 172.40.255.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0
