---
name: lemp

x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: ${LOG_MAX_SIZE}
      max-file: ${LOG_MAX_FILE}

services:
  www:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: www
    hostname: www
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_PREFIX}.${NGINX_IPV4}
      proxynet:
    restart: unless-stopped
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet
      - traefik.http.routers.www.rule=Host(`www.stage.local`)
    <<: *default-logging

  php:
    image: php-mysql:${PHP_IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    hostname: php
    volumes:
      - ./html:/var/www/html
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_PREFIX}.${PHP_IPV4}
    restart: unless-stopped
    <<: *default-logging

  db:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=stage
    volumes:
      - datadb:/var/lib/mysql
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_PREFIX}.${MARIADB_IPV4}
    restart: unless-stopped
    <<: *default-logging

volumes:
  datadb:

networks:
  lempnet:
    ipam:
      config:
        - subnet: ${LEMPNET_PREFIX}.0.0/16
          gateway: 172.40.255.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0
  proxynet:
    external: true
