---
services:
  busy:
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    container_name: busy
    restart: unless-stopped

  php:
    environment:
      - STAGE=DOCKER

  db:
    environment:
      - MARIADB_DATABASE=stage
