---
name: lemp

services:
  www:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: www
    hostname: www
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_PREFIX}.${NGINX_IPV4}
    restart: unless-stopped
    depends_on:
      - php

  php:
    image: php:${PHP_IMAGE_TAG}
    container_name: php
    hostname: php
    volumes:
      - ./html:/var/www/html
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_PREFIX}.${PHP_IPV4}
    restart: unless-stopped

  db:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - datadb:/var/lib/mysql
    networks:
      lempnet:
        ipv4_address: ${LEMPNET_PREFIX}.${MARIADB_IPV4}
    restart: unless-stopped

volumes:
  datadb:

networks:
  lempnet:
    ipam:
      config:
        - subnet: ${LEMPNET_PREFIX}.0.0/16
          gateway: 172.40.255.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0
